# Generated by Django 5.0.2 on 2024-02-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IT_Markaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('ticher_count', models.IntegerField()),
                ('talaba_count', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
