# Generated by Django 5.0.2 on 2024-02-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_markaz',
            name='name',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
