# Generated by Django 5.0.2 on 2024-02-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_it_markaz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_markaz',
            name='bool_field',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
