# Generated by Django 5.0.2 on 2024-02-20 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_it_markaz_bool_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_markaz',
            name='date_auto',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
