# Generated by Django 5.0.2 on 2024-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_it_markaz_date_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_markaz',
            name='date_auto_now',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='it_markaz',
            name='date_auto',
            field=models.DateField(auto_now_add=True),
        ),
    ]
