# Generated by Django 5.0.2 on 2024-02-20 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_it_markaz_date_auto_now_alter_it_markaz_date_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_markaz',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
