# Generated by Django 5.0.2 on 2024-02-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_it_markaz_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_aut', models.DateTimeField(auto_now=True)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_field', models.DurationField()),
            ],
        ),
    ]
