# Generated by Django 5.0.2 on 2024-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_samdu'),
    ]

    operations = [
        migrations.AddField(
            model_name='samdu',
            name='email_field',
            field=models.EmailField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
