# Generated by Django 5.0.2 on 2024-02-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_samdu_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='samdu',
            name='Float field: ',
            field=models.FloatField(default=1.1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='samdu',
            name='email_field',
            field=models.EmailField(max_length=16),
        ),
    ]
