# Generated by Django 5.0.2 on 2024-02-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_samdu_float_field__alter_samdu_email_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samdu',
            name='Float field: ',
        ),
    ]
