# Generated by Django 5.0.2 on 2024-02-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_samdu_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='samdu',
            name='file_path_field',
            field=models.FilePathField(blank=True, verbose_name='FilePathField '),
        ),
        migrations.AlterField(
            model_name='samdu',
            name='file_field',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/', verbose_name='File yuklash '),
        ),
    ]
