# Generated by Django 5.0.2 on 2024-02-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_samdu_file_path_field_alter_samdu_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samdu',
            name='file_path_field',
            field=models.FilePathField(verbose_name='FilePathField '),
        ),
    ]
