# Generated by Django 5.0.2 on 2024-02-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_samdu_file_path_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samdu',
            name='file_path_field',
            field=models.FilePathField(path='https://media.istockphoto.com/id/1171813546/photo/flint-hills-traffic.jpg?s=612x612&w=is&k=20&c=73gHGDt7R7VsGzPwqJPuiG3b-kkVth7MD-lhDRZ6sEw=', verbose_name='FilePathField '),
        ),
    ]
