# Generated by Django 5.0.2 on 2024-02-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_samdu_file_path_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samdu',
            name='file_path_field',
            field=models.FilePathField(),
        ),
    ]
