# Generated by Django 5.0.2 on 2024-02-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_samdu_file_path_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=10, verbose_name='Ism ')),
                ('familya', models.CharField(max_length=12, verbose_name='Familya ')),
                ('email_faild', models.EmailField(max_length=20, verbose_name='Elektron poshta manzili ')),
                ('phone_field', models.IntegerField(max_length=10, verbose_name='Telefon raqam ')),
                ('taxallus_field', models.CharField(max_length=10, verbose_name='Taxallus ')),
                ('viloyat', models.CharField(max_length=12, verbose_name='Viloyat ')),
                ('Tuman', models.CharField(max_length=10, verbose_name='Tuman ')),
                ('talim', models.TextField(verbose_name="O'qish joy ")),
                ('kurs', models.IntegerField(max_length=2, verbose_name='Kursi yoki sinifi ')),
                ('bool_field', models.BooleanField(verbose_name="Agar o'qish jpyingiz yuqorida qayd etilmagan bo'lsa yoki biror joyda ishlasangiz buni tanlang va quyidagilarni to'ldiring")),
                ('now_date', models.DateField(verbose_name="Ro'yxatdan o'tilgan kun")),
                ('now_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='samdu',
            name='file_path_field',
        ),
    ]
